name: Copilot Metrics Collector

on:
  schedule:
    - cron: "0 1 * * *"   # Täglich um 01:00 UTC
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create output folder
        run: mkdir -p copilot-metrics

      - name: Fetch GitHub Copilot Metrics
        env:
          GITHUB_TOKEN: ${{ secrets.COPILOT_TOKEN }}
        run: |
          DATE=$(date +"%Y-%m-%d")
          OUTPUT="copilot-metrics/metrics-$DATE.json"

          # Beispiel: User metrics (kein PAT nötig)
          # API: GET https://api.github.com/user/copilot/metrics

          curl -s \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/user/copilot/metrics \
            > $OUTPUT

          echo "Saved metrics to $OUTPUT"

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add copilot-metrics/
          git commit -m "Daily Copilot metrics $(date)" || echo "No changes to commit"
          git push
